In [1]:
import pandas as pd

# Load the dataset
df = pd.read_csv('/content/africa_pharmacovigilance_dataset_FIXED.csv')

# Display the first 5 rows of the DataFrame
display(df.head())

,report_id,report_date,country,region,subregion,drug_name_generic,drug_name_brand,drug_class,atc_code,route_of_administration,...,patient_sex,patient_weight_kg,comorbidities,concomitant_medications,rechallenge,dechallenge,outcome,reporter_type,data_source,notes
0,AFPV-2024-KE-0001,2024-01-05,Kenya,East Africa,Greater Horn of Africa,Artemether + Lumefantrine,Coartem,Antimalarial,P01BF01,Oral,...,Female,58.0,NaN,Metoclopramide,Not rechallenged,Event resolved on discontinuation,Recovered,Pharmacist,WHO VigiAccess / PPB Kenya,QTc >480ms recorded on ECG day 2 of treatment
1,AFPV-2024-KE-0002,2024-01-11,Kenya,East Africa,Greater Horn of Africa,Efavirenz,Stocrin,Antiretroviral (NNRTI),J05AG03,Oral,...,Male,72.0,Depression,Cotrimoxazole,Not rechallenged,Switched to Dolutegravir,Recovered with sequelae,Clinician,PPB Kenya,Patient reported persistent neuropsychiatric s...
2,AFPV-2024-NG-0001,2024-01-15,Nigeria,West Africa,Gulf of Guinea,Amodiaquine + Artesunate,ASAQ Winthrop,Antimalarial,P01BA06,Oral,...,Male,19.0,Malnutrition,NaN,Not rechallenged,Discontinued; supportive care,Hospitalized - not recovered,Clinician,NAFDAC Nigeria,ANC <500 cells/µL; required G-CSF support
3,AFPV-2024-NG-0002,2024-01-22,Nigeria,West Africa,Gulf of Guinea,Pyrimethamine + Sulfadoxine,Fansidar,Antimalarial,P01BD51,Oral,...,Female,61.0,Pregnancy (2nd trimester),Ferrous sulfate + Folic acid,Not rechallenged,Discontinued; dermatology referral,Hospitalized - recovering,Clinician,NAFDAC Nigeria,Extensive mucocutaneous involvement; ICU admis...
4,AFPV-2024-ET-0001,2024-01-28,Ethiopia,East Africa,Horn of Africa,Isoniazid,Rimifon,Antitubercular,J04AC01,Oral,...,Male,65.0,Alcohol use disorder,Rifampicin + Pyrazinamide + Ethambutol,Not rechallenged,Regimen held; monitoring,Recovering,Clinician,Ethiopian Food and Drug Authority,ALT >10x ULN; jaundice present

In [2]:
# Display basic information about the DataFrame, including data types and non-null values
display(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 71 entries, 0 to 70
Data columns (total 34 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   report_id                71 non-null     object
 1   report_date              71 non-null     object
 2   country                  71 non-null     object
 3   region                   71 non-null     object
 4   subregion                71 non-null     object
 5   drug_name_generic        71 non-null     object
 6   drug_name_brand          71 non-null     object
 7   drug_class               71 non-null     object
 8   atc_code                 71 non-null     object
 9   route_of_administration  71 non-null     object
 10  dose_mg                  71 non-null     object
 11  dose_frequency           71 non-null     object
 12  duration_of_use_days     71 non-null     int64
 13  indication               71 non-null     object
 14  adverse_event            71 non-null     object
 15  adverse_event_meddra_pt  71 non-null     object
 16  system_organ_class       71 non-null     object
 17  severity                 71 non-null     object
 18  severity_score           71 non-null     int64
 19  seriousness              71 non-null     object
 20  causality_assessment     71 non-null     object
 21  time_to_onset_days       70 non-null     float64
 22  patient_age_group        71 non-null     object
 23  patient_age_years        71 non-null     int64
 24  patient_sex              71 non-null     object
 25  patient_weight_kg        71 non-null     float64
 26  comorbidities            44 non-null     object
 27  concomitant_medications  51 non-null     object
 28  rechallenge              71 non-null     object
 29  dechallenge              71 non-null     object
 30  outcome                  71 non-null     object
 31  reporter_type            71 non-null     object
 32  data_source              71 non-null     object
 33  notes                    71 non-null     object
dtypes: float64(2), int64(3), object(29)
memory usage: 19.0+ KB

None

In [3]:
# Display descriptive statistics of the DataFrame
display(df.describe(include='all'))

,report_id,report_date,country,region,subregion,drug_name_generic,drug_name_brand,drug_class,atc_code,route_of_administration,...,patient_sex,patient_weight_kg,comorbidities,concomitant_medications,rechallenge,dechallenge,outcome,reporter_type,data_source,notes
count,71,71,71,71,71,71,71,71,71,71,...,71,71.000000,44,51,71,71,71,71,71,71
unique,71,71,26,5,11,66,65,49,63,5,...,2,NaN,36,49,11,65,11,9,28,71
top,AFPV-2024-KE-0001,2024-01-05,Kenya,East Africa,Gulf of Guinea,Quinine,Fansidar,Antimalarial,P01BC01,Oral,...,Male,NaN,Malnutrition,Fluconazole,Not rechallenged,Not applicable,Hospitalized - recovered,Clinician,Ethiopian Food and Drug Authority,QTc >480ms recorded on ECG day 2 of treatment
freq,1,1,6,30,18,2,2,12,3,57,...,39,NaN,3,2,60,7,23,54,6,1
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,60.988732,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,17.613238,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,3.200000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,56.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,64.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,70.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,95.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
# Convert 'dose_mg' to numeric, coercing errors to NaN
df['dose_mg'] = pd.to_numeric(df['dose_mg'], errors='coerce')

# Fill any NaN values created by coercion with the median
df['dose_mg'] = df['dose_mg'].fillna(df['dose_mg'].median())

# Convert 'dose_frequency' to numeric, coercing errors to NaN
df['dose_frequency'] = pd.to_numeric(df['dose_frequency'], errors='coerce')

# Fill any NaN values created by coercion with a sensible default
# If all values are NaN, mode() will return an empty Series, causing KeyError
mode_freq = df['dose_frequency'].mode()
if not mode_freq.empty:
    df['dose_frequency'] = df['dose_frequency'].fillna(mode_freq[0])
else:
    # If no mode exists (all NaN), fill with a default value, e.g., 1 (once daily)
    df['dose_frequency'] = df['dose_frequency'].fillna(1)

# Convert 'report_date' to datetime objects
df['report_date'] = pd.to_datetime(df['report_date'])

# Verify data types after conversion
display(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 71 entries, 0 to 70
Data columns (total 34 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   report_id                71 non-null     object
 1   report_date              71 non-null     datetime64[ns]
 2   country                  71 non-null     object
 3   region                   71 non-null     object
 4   subregion                71 non-null     object
 5   drug_name_generic        71 non-null     object
 6   drug_name_brand          71 non-null     object
 7   drug_class               71 non-null     object
 8   atc_code                 71 non-null     object
 9   route_of_administration  71 non-null     object
 10  dose_mg                  71 non-null     float64
 11  dose_frequency           71 non-null     float64
 12  duration_of_use_days     71 non-null     int64
 13  indication               71 non-null     object
 14  adverse_event            71 non-null     object
 15  adverse_event_meddra_pt  71 non-null     object
 16  system_organ_class       71 non-null     object
 17  severity                 71 non-null     object
 18  severity_score           71 non-null     int64
 19  seriousness              71 non-null     object
 20  causality_assessment     71 non-null     object
 21  time_to_onset_days       71 non-null     float64
 22  patient_age_group        71 non-null     object
 23  patient_age_years        71 non-null     int64
 24  patient_sex              71 non-null     object
 25  patient_weight_kg        71 non-null     float64
 26  comorbidities            71 non-null     object
 27  concomitant_medications  71 non-null     object
 28  rechallenge              71 non-null     object
 29  dechallenge              71 non-null     object
 30  outcome                  71 non-null     object
 31  reporter_type            71 non-null     object
 32  data_source              71 non-null     object
 33  notes                    71 non-null     object
dtypes: datetime64[ns](1), float64(4), int64(3), object(26)
memory usage: 19.0+ KB

None

In [5]:
# Verify data types and null counts after cleaning
display(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 71 entries, 0 to 70
Data columns (total 34 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   report_id                71 non-null     object
 1   report_date              71 non-null     object
 2   country                  71 non-null     object
 3   region                   71 non-null     object
 4   subregion                71 non-null     object
 5   drug_name_generic        71 non-null     object
 6   drug_name_brand          71 non-null     object
 7   drug_class               71 non-null     object
 8   atc_code                 71 non-null     object
 9   route_of_administration  71 non-null     object
 10  dose_mg                  71 non-null     float64
 11  dose_frequency           0 non-null      float64
 12  duration_of_use_days     71 non-null     int64
 13  indication               71 non-null     object
 14  adverse_event            71 non-null     object
 15  adverse_event_meddra_pt  71 non-null     object
 16  system_organ_class       71 non-null     object
 17  severity                 71 non-null     object
 18  severity_score           71 non-null     int64
 19  seriousness              71 non-null     object
 20  causality_assessment     71 non-null     object
 21  time_to_onset_days       70 non-null     float64
 22  patient_age_group        71 non-null     object
 23  patient_age_years        71 non-null     int64
 24  patient_sex              71 non-null     object
 25  patient_weight_kg        71 non-null     float64
 26  comorbidities            44 non-null     object
 27  concomitant_medications  51 non-null     object
 28  rechallenge              71 non-null     object
 29  dechallenge              71 non-null     object
 30  outcome                  71 non-null     object
 31  reporter_type            71 non-null     object
 32  data_source              71 non-null     object
 33  notes                    71 non-null     object
dtypes: float64(4), int64(3), object(27)
memory usage: 19.0+ KB

None

In [9]:
# Analyze the most frequent adverse events
most_common_adverse_events = df['adverse_event'].value_counts().head(10)
display("Top 10 Most Common Adverse Events:", most_common_adverse_events)

# Analyze the drugs most frequently associated with adverse events
# Group by drug and count the number of adverse events for each drug
drug_adverse_event_counts = df.groupby('drug_name_generic')['adverse_event'].count().sort_values(ascending=False).head(10)
display("Top 10 Drugs Associated with Adverse Events:", drug_adverse_event_counts)

'Top 10 Most Common Adverse Events:'

adverse_event
Prolonged QTc interval                                           1
Vivid nightmares and suicidal ideation                           1
Severe neutropenia                                               1
Stevens-Johnson Syndrome                                         1
Drug-induced hepatotoxicity                                      1
Thrombocytopenic purpura                                         1
Significant weight gain and metabolic syndrome                   1
Drug reaction with eosinophilia and systemic symptoms (DRESS)    1
Irreversible retinopathy                                         1
Peripheral neuropathy                                            1
Name: count, dtype: int64

'Top 10 Drugs Associated with Adverse Events:'

drug_name_generic
Ofloxacin                   2
Rifampicin                  2
Hydroxychloroquine          2
Quinine                     2
Mefloquine                  2
Abacavir                    1
Acyclovir                   1
Albendazole                 1
Amodiaquine + Artesunate    1
Amiodarone                  1
Name: adverse_event, dtype: int64

In [20]:
# drug-symptom correlation and causality assessment with corrected filters
drug_symptom_correlation = df.groupby(['drug_name_generic', 'adverse_event']).size().reset_index(name='count')
drug_symptom_correlation_sorted = drug_symptom_correlation.sort_values(by='count', ascending=False).head(10)
display("Top 10 Drug-Adverse Event Correlations:", drug_symptom_correlation_sorted)

causality_assessment_counts = df['causality_assessment'].value_counts()
display("Causality Assessment Counts:", causality_assessment_counts)

high_causality_drugs = df[df['causality_assessment'].isin(['Definite', 'Probable'])]
high_causality_drug_counts = high_causality_drugs['drug_name_generic'].value_counts().head(10)
display("Top 10 Drugs with High Causality Assessment:", high_causality_drug_counts)

'Top 10 Drug-Adverse Event Correlations:'

,drug_name_generic,adverse_event,count
0,Abacavir,Abacavir hypersensitivity reaction,1
1,Acyclovir,Crystalluria and obstructive nephropathy,1
2,Albendazole,Elevated liver enzymes (DILI),1
3,Amiodarone,Amiodarone-induced thyrotoxicosis type II,1
4,Amodiaquine + Artesunate,Severe neutropenia,1
5,Amoxicillin + Clavulanate,Cholestatic jaundice,1
6,Amphotericin B (conventional),Nephrotoxicity and electrolyte wasting,1
7,Artemether,Fetal bradycardia and preterm labor,1
8,Artemether + Lumefantrine,Prolonged QTc interval,1
9,Artesunate,Post-artesunate delayed hemolysis,1

'Causality Assessment Counts:'

causality_assessment
Definite    34
Probable    33
Possible     4
Name: count, dtype: int64

'Top 10 Drugs with High Causality Assessment:'

drug_name_generic
Rifampicin            2
Quinine               2
Hydroxychloroquine    2
Mefloquine            2
Ofloxacin             2
Efavirenz             1
Isoniazid             1
Dolutegravir          1
Chloroquine           1
Nevirapine            1
Name: count, dtype: int64